"""add createdAt and updatedAt columns to feedback table

Revision ID: e792fbd4541c
Revises: de2ff3619e21
Create Date: 2024-06-07 11:37:59.354527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e792fbd4541c'
down_revision: Union[str, None] = 'de2ff3619e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('feedback', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'updated_at')
    op.drop_column('feedback', 'created_at')
    # ### end Alembic commands ###
